all:
  hosts:
    winhamd:
      ansible_host: 172.167.147.204    # Replace with Terraform output
      ansible_user: mujju
      ansible_password: Muzzammil@752
      ansible_connection: winrm
      ansible_winrm_transport: basic
      ansible_port: 5985
